name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - run: npm ci

      - run: npm run build
        env:
          PUBLIC_URL: keybr.com

      - name: Generate index.html
        run: node .github/workflows/generate-html.js
        env:
          PUBLIC_URL: keybr.com

      - name: Create .nojekyll
        run: touch ./root/public/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./root/public
          publish_branch: gh-pages
